# Generated by Django 2.2.5 on 2020-04-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200413_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Url de imagen'),
        ),
    ]
