# Generated by Django 2.2.5 on 2020-05-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200515_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Teléfono'),
        ),
    ]
