# Generated by Django 2.2.5 on 2019-09-28 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la familia')),
            ],
        ),
        migrations.CreateModel(
            name='PlantSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100, verbose_name='Nombre común')),
                ('scientific_name', models.CharField(max_length=100, unique=True, verbose_name='Nombre científico')),
                ('description', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/plant_family', verbose_name='Imagen')),
                ('family', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_site.PlantFamily', verbose_name='familia')),
            ],
            options={
                'verbose_name': 'Categorias de clima',
                'verbose_name_plural': 'Categorias de climas',
            },
        ),
    ]
