# Generated by Django 2.2.5 on 2019-10-03 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantfamily',
            options={'verbose_name': 'Familias de plantas', 'verbose_name_plural': 'Familias de plantas'},
        ),
        migrations.AlterModelOptions(
            name='plantspecies',
            options={'verbose_name': 'Especies de Plantas', 'verbose_name_plural': 'Especies de plantas'},
        ),
    ]
