# Generated by Django 2.2.5 on 2019-10-19 06:14

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_auto_20191003_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recolector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='SpecimenStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='PlantSpecimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='uploads/specimen', verbose_name='Specimen Photo')),
                ('date_recieved', models.DateField(verbose_name='Fecha')),
                ('plant_family', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_site.PlantFamily', verbose_name='Family')),
                ('plant_species', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='plant_family', chained_model_field='PlantFamily', on_delete=django.db.models.deletion.CASCADE, to='main_site.PlantSpecies')),
                ('recolector', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_site.Recolector', verbose_name='Recolector')),
                ('status', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_site.SpecimenStatus', verbose_name='Status')),
            ],
        ),
    ]
