# Generated by Django 2.2.5 on 2019-10-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_plantspecimen_recolector_specimenstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='recolector',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/recolectors', verbose_name='Recolector photo'),
        ),
    ]
