# Generated by Django 2.2.5 on 2019-10-19 06:32

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0007_auto_20191019_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantspecimen',
            name='plant_species',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='plant_family', chained_model_field='family', on_delete=django.db.models.deletion.CASCADE, to='main_site.PlantSpecies'),
        ),
    ]
