# Generated by Django 2.2.5 on 2019-10-19 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0008_auto_20191019_0132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantspecimen',
            options={'verbose_name': 'Espécimen', 'verbose_name_plural': 'Especimenes'},
        ),
        migrations.AlterModelOptions(
            name='recolector',
            options={'verbose_name': 'Recolector', 'verbose_name_plural': 'recolectores'},
        ),
        migrations.AlterModelOptions(
            name='specimenstatus',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.RenameField(
            model_name='plantspecimen',
            old_name='date_recieved',
            new_name='date_received',
        ),
    ]
