# Generated by Django 2.2.5 on 2019-10-26 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0010_auto_20191026_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantspecimen',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='Perfil'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
