# Generated by Django 2.2.5 on 2019-10-27 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_site', '0011_auto_20191026_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantspecimen',
            name='profile',
        ),
        migrations.AddField(
            model_name='plantspecimen',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Perfil'),
        ),
    ]
