# Generated by Django 2.2.5 on 2019-11-10 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_site', '0012_auto_20191026_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biostatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de estado biológico')),
            ],
        ),
        migrations.CreateModel(
            name='CapTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de sombrero de hongo',
                'verbose_name_plural': 'Tipos de sombrero de hongo',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Ciudad/Municipio',
                'verbose_name_plural': 'Ciudades/Municipios',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Ecosystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de hábitat')),
            ],
            options={
                'verbose_name': 'Ecosistema',
                'verbose_name_plural': 'Ecosistemas',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la familia')),
                ('type', models.CharField(choices=[('planta', 'Planta'), ('hongo', 'Hongo')], max_length=100, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Familias de plantas',
                'verbose_name_plural': 'Familias de plantas',
            },
        ),
        migrations.CreateModel(
            name='FormTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de forma de hongo',
                'verbose_name_plural': 'Tipos de forma de hongos',
            },
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Género')),
                ('type', models.CharField(choices=[('planta', 'Planta'), ('hongo', 'Hongo')], max_length=100, verbose_name='Tipo')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Family', verbose_name='Familia')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.CreateModel(
            name='MushroomSpecimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='uploads/specimen', verbose_name='Foto')),
                ('date_received', models.DateField(verbose_name='Fecha')),
                ('number_of_samples', models.PositiveIntegerField(verbose_name='Número de ejemplares')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('latitude', models.FloatField(verbose_name='Latitud')),
                ('longitude', models.FloatField(verbose_name='Longitud')),
                ('location', models.CharField(max_length=100, verbose_name='Ubicación')),
                ('crust', models.BooleanField(verbose_name='¿Tiene costra?')),
                ('color', models.CharField(max_length=100, verbose_name='color')),
                ('change_of_color', models.CharField(max_length=100, verbose_name='Cambios de color')),
                ('smell', models.CharField(max_length=100, verbose_name='olor')),
                ('aditional_info', models.TextField(verbose_name='Información Adicional')),
                ('cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.CapTypes', verbose_name='Forma de sombrero')),
                ('city', smart_selects.db_fields.ChainedForeignKey(chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='main_site.City', verbose_name='Ciudad/Municipio')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Country', verbose_name='País')),
                ('ecosystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Ecosystem', verbose_name='Ecosistema')),
                ('family', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_site.Family', verbose_name='Family')),
                ('forms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.FormTypes', verbose_name='Forma de hongo')),
            ],
            options={
                'verbose_name': 'Espécimen de hongo',
                'verbose_name_plural': 'Especimenes de hongos',
            },
        ),
        migrations.CreateModel(
            name='RecolectionAreaStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Área de recolección')),
            ],
            options={
                'verbose_name': 'Área de recolección',
                'verbose_name_plural': 'Áreas de recolección',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100, verbose_name='Nombre común')),
                ('scientific_name', models.CharField(max_length=100, unique=True, verbose_name='Nombre científico')),
                ('description', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/plant_family', verbose_name='Imagen')),
                ('type', models.CharField(choices=[('planta', 'Planta'), ('hongo', 'Hongo')], max_length=100, verbose_name='Tipo')),
                ('family', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_site.Family', verbose_name='familia')),
                ('genus', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='family', chained_model_field='family', on_delete=django.db.models.deletion.CASCADE, to='main_site.Genus')),
            ],
            options={
                'verbose_name': 'Especies de Plantas',
                'verbose_name_plural': 'Especies de plantas',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Country', verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'Estado/Departamentos/Provincias',
                'verbose_name_plural': 'Estados/Departamentos/Provincias',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.RemoveField(
            model_name='plantspecies',
            name='family',
        ),
        migrations.AlterModelOptions(
            name='plantspecimen',
            options={'verbose_name': 'Espécimen de planta', 'verbose_name_plural': 'Especimenes de plantas'},
        ),
        migrations.RemoveField(
            model_name='plantspecimen',
            name='plant_family',
        ),
        migrations.RemoveField(
            model_name='plantspecimen',
            name='plant_species',
        ),
        migrations.AddField(
            model_name='plantspecimen',
            name='complete',
            field=models.BooleanField(default=True, verbose_name='Completo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantspecimen',
            name='description',
            field=models.TextField(default=1, verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantspecimen',
            name='latitude',
            field=models.FloatField(default=1, verbose_name='Latitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantspecimen',
            name='location',
            field=models.CharField(default=1, max_length=100, verbose_name='Ubicación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantspecimen',
            name='longitude',
            field=models.FloatField(default=1, verbose_name='Longitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantspecimen',
            name='number_of_samples',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de ejemplares'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plantspecimen',
            name='photo',
            field=models.ImageField(upload_to='uploads/specimen', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='plantspecimen',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Status', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='plantspecimen',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.DeleteModel(
            name='PlantFamily',
        ),
        migrations.DeleteModel(
            name='PlantSpecies',
        ),
        migrations.DeleteModel(
            name='SpecimenStatus',
        ),
        migrations.AddField(
            model_name='mushroomspecimen',
            name='recolection_area_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.RecolectionAreaStatus', verbose_name='Estado del area de recolección'),
        ),
        migrations.AddField(
            model_name='mushroomspecimen',
            name='species',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='family', chained_model_field='family', on_delete=django.db.models.deletion.CASCADE, to='main_site.Species'),
        ),
        migrations.AddField(
            model_name='mushroomspecimen',
            name='state',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='country', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, to='main_site.State', verbose_name='Estado/Departamento/Provincia'),
        ),
        migrations.AddField(
            model_name='mushroomspecimen',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Status', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='mushroomspecimen',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.State', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='plantspecimen',
            name='biostatus',
            field=models.ForeignKey(default= 1, on_delete=django.db.models.deletion.CASCADE, to='main_site.Biostatus', verbose_name='Biostatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantspecimen',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='state', chained_model_field='state', default=1, on_delete=django.db.models.deletion.CASCADE, to='main_site.City', verbose_name='Ciudad/Municipio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantspecimen',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_site.Country', verbose_name='País'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantspecimen',
            name='ecosystem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_site.Ecosystem', verbose_name='Ecosistema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantspecimen',
            name='family',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_site.Family', verbose_name='Family'),
        ),
        migrations.AddField(
            model_name='plantspecimen',
            name='recolection_area_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_site.RecolectionAreaStatus', verbose_name='Estado del area de recolección'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantspecimen',
            name='species',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='family', chained_model_field='family', default=1, on_delete=django.db.models.deletion.CASCADE, to='main_site.Species'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantspecimen',
            name='state',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='country', chained_model_field='country', default=1, on_delete=django.db.models.deletion.CASCADE, to='main_site.State', verbose_name='Estado/Departamento/Provincia'),
            preserve_default=False,
        ),
    ]
