# Generated by Django 2.2.5 on 2019-11-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0017_auto_20191109_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushroomspecimen',
            name='approved',
            field=models.BooleanField(blank=True, default=False, verbose_name='Aprobado'),
        ),
        migrations.AddField(
            model_name='plantspecimen',
            name='approved',
            field=models.BooleanField(blank=True, default=False, verbose_name='Aprobado'),
        ),
    ]
