# Generated by Django 2.2.5 on 2019-11-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0018_auto_20191127_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushroomspecimen',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Aprobado'),
        ),
        migrations.AlterField(
            model_name='plantspecimen',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Aprobado'),
        ),
    ]
