# Generated by Django 2.2.5 on 2020-03-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0019_auto_20191127_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushroomspecimen',
            name='approved',
            field=models.BooleanField(blank=True, default=False, verbose_name='Aprobado'),
        ),
        migrations.AlterField(
            model_name='plantspecimen',
            name='approved',
            field=models.BooleanField(blank=True, default=False, verbose_name='Aprobado'),
        ),
    ]
