# Generated by Django 2.2.5 on 2020-03-27 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0020_auto_20200318_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genus',
            name='type',
        ),
        migrations.RemoveField(
            model_name='mushroomspecimen',
            name='country',
        ),
        migrations.RemoveField(
            model_name='mushroomspecimen',
            name='family',
        ),
        migrations.RemoveField(
            model_name='mushroomspecimen',
            name='genus',
        ),
        migrations.RemoveField(
            model_name='mushroomspecimen',
            name='state',
        ),
        migrations.RemoveField(
            model_name='plantspecimen',
            name='country',
        ),
        migrations.RemoveField(
            model_name='plantspecimen',
            name='family',
        ),
        migrations.RemoveField(
            model_name='plantspecimen',
            name='genus',
        ),
        migrations.RemoveField(
            model_name='plantspecimen',
            name='state',
        ),
        migrations.RemoveField(
            model_name='species',
            name='family',
        ),
        migrations.RemoveField(
            model_name='species',
            name='type',
        ),
        migrations.AlterField(
            model_name='mushroomspecimen',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Species', verbose_name='Especie'),
        ),
        migrations.AlterField(
            model_name='plantspecimen',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Species', verbose_name='Especie'),
        ),
        migrations.AlterField(
            model_name='species',
            name='genus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.Genus', verbose_name='Género'),
        ),
    ]
