# Generated by Django 2.2.5 on 2020-04-13 20:48

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0021_auto_20200326_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushroomspecimen',
            name='date_received',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='mushroomspecimen',
            name='photo',
            field=models.ImageField(default='/static/img/default.jpg', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='uploads/specimen', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='plantspecimen',
            name='date_received',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='plantspecimen',
            name='photo',
            field=models.ImageField(default='/static/img/default.jpg', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='uploads/specimen', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='species',
            name='photo',
            field=models.ImageField(default='/static/img/default.jpg', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='uploads/plant_family', verbose_name='Imagen'),
        ),
    ]
