# Generated by Django 2.2.5 on 2020-04-13 22:37

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0027_species_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='photos',
        ),
        migrations.AddField(
            model_name='mushroomspecimen',
            name='photos',
            field=models.ImageField(default='/home/javier/plants_api_project/plants_api/staticfiles/img/default.jpg', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='uploads/plant_family', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='plantspecimen',
            name='photos',
            field=models.ImageField(default='/home/javier/plants_api_project/plants_api/staticfiles/img/default.jpg', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='uploads/plant_family', verbose_name='Imagen'),
        ),
    ]
