# Generated by Django 2.2.5 on 2020-04-13 22:39

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0028_auto_20200413_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mushroomspecimen',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='plantspecimen',
            name='photos',
        ),
        migrations.AlterField(
            model_name='mushroomspecimen',
            name='photo',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='uploads/plant_family', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='plantspecimen',
            name='photo',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='uploads/plant_family', verbose_name='Imagen'),
        ),
    ]
