# Generated by Django 2.2.5 on 2020-04-13 22:40

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0029_auto_20200413_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='photo',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='uploads/plant_family', verbose_name='Imagen'),
        ),
    ]
