# Generated by Django 2.2.5 on 2020-04-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0031_auto_20200415_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushroomspecimen',
            name='photo_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Url de imagen'),
        ),
        migrations.AddField(
            model_name='plantspecimen',
            name='photo_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Url de imagen'),
        ),
    ]
