# Generated by Django 2.2.5 on 2020-04-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0032_auto_20200416_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='photo_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Url de imagen'),
        ),
    ]
