# Generated by Django 2.2.5 on 2020-05-28 08:35

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0033_species_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mushroomspecimen',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='plantspecimen',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='species',
            name='photo_url',
        ),
        migrations.AlterField(
            model_name='mushroomspecimen',
            name='photo',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(permissions=(gdstorage.storage.GoogleDriveFilePermission(gdstorage.storage.GoogleDrivePermissionRole('reader'), gdstorage.storage.GoogleDrivePermissionType('anyone')),)), upload_to='uploads/plant_family', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='plantspecimen',
            name='photo',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(permissions=(gdstorage.storage.GoogleDriveFilePermission(gdstorage.storage.GoogleDrivePermissionRole('reader'), gdstorage.storage.GoogleDrivePermissionType('anyone')),)), upload_to='uploads/plant_family', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='species',
            name='photo',
            field=models.ImageField(upload_to='uploads/plant_family', verbose_name='Imagen'),
        ),
    ]
